# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/nuxt-animation"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-api"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-bootstrap"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-content"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-dx"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-fa"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-formkit"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-icones"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-image"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-layouts"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-middleware"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-minimal"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-pages"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-pinia"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-plugins"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-simple"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-supabase"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-tailwind"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-ui"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-use"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/nuxt-utils"
    schedule:
      interval: "monthly"
      time: "05:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
