allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@nuxt/kit@4.6.0"
  - "@nuxt/nitro-server@4.6.0"
  - "@nuxt/schema@4.6.0"
  - "@nuxt/vite-builder@4.6.0"
  - "@nuxt/vite-server@4.6.0"
  - nuxt@4.6.0
overrides:
  '@simple-git/argv-parser@<2.0.1': ^2.0.1
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  simple-git@<=3.36.0: ^4.0.0
  simple-git@>=3.15.0 <4.0.1: ^4.0.1
