-- sample data for nuxt-supabase example
-- last revision: 2023-10-29

DROP TABLE IF EXISTS "nuxt_items";

CREATE TABLE "nuxt_items" (
	"id"	integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"name"	varchar(50) NOT NULL,
	"dscr"	varchar(255) NOT NULL,
	"image"	varchar(100) NOT NULL
);

-- data generated by ChatGPT-4 on 2023-10-19
INSERT INTO "nuxt_items"("name", "dscr", "image") VALUES
('Whispers of Dawn', 'An enchanting depiction of the early morning, where soft hues of pink and orange gently embrace the silhouettes of waking life.', '01.jpg'),
('Celestial Dance', 'A captivating cosmic scene highlighting the mesmerizing ballet of stars and nebulae, celebrating the eternal dance of the universe.', '02.jpg'),
('Harmony in Chaos', 'This piece artistically captures the raw emotion and swirling intensity found within life’s most turbulent moments, yet finds peace in the uproar.', '03.jpg'),
('Forgotten Summer', 'Nostalgic imagery filled with warm, sun-bleached colors, detailing a serene landscape that echoes with the laughter and joy of a past season.', '04.jpg'),
('Urban Silence', 'A stark yet beautiful portrayal of a deserted cityscape, where modern architecture meets the profound stillness of the human-free environment.', '05.jpg'),
('Ephemeral Blooms', 'A delicate representation of fleeting beauty, with the ethereal grace of blossoms depicted in a transient, almost ghostly manner.', '06.jpg'),
('Serenade of the Seas', 'The powerful rhythm of the ocean is brought to life with vibrant blues and stormy greys, encapsulating both the calm and the fury in a sailor’s melody.', '07.jpg'),
('Mystic Echoes', 'Set in a deep, haunting forest, this painting reflects the ancient wisdom and mystical whispers that could be heard in the rustle of its leaves.', '08.jpg'),
('Frozen in Time', 'The stark beauty of winter is immortalized forever in this scene, where icy blues and whites reveal a serene, frozen landscape untouched by warmth.', '09.jpg'),
('Rhapsody in Rouge', 'A passionate display using varying shades of red to convey love, anger, passion, and every human emotion in-between, all in an abstract, captivating form.', '10.jpg'),
('Echoes of Tranquility', 'A serene lakeside scene at dusk, where the calm water reflects the fading hues of the sunset, encapsulating a perfect moment of peace.', '11.jpg'),
('Vortex of Illusions', 'An abstract piece that plunges the viewer into a swirling realm of colors and shapes, challenging the boundaries between reality and fantasy.', '12.jpg');